version: '3'

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:80"
    networks:
      - mynetwork
    depends_on:
      - rabbitmq
      - mongo

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongodbdata:/data/db
    networks:
      - mynetwork

volumes:
  mongodbdata:

networks:
  mynetwork:
    driver: bridge